move trap instruction in hawk and awkcel to the end

diff --git a/bin/awkcel b/bin/awkcel
--- a/bin/awkcel
+++ b/bin/awkcel
@@ -49,7 +49,6 @@ echo "$BASENAME" | grep "[ $TAB]" && die "Shell script names really REALLY shoul
 
 # Temporary Filename + Directory (both, you can use either, note they'll have different random stuff in the XXXXXX part)
 TMPDIR=`mktemp -d /tmp/$BASENAME.XXXXXX`
- trap "/bin/rm -rf $TMPDIR; exit" 0 1 2 3 15 # call trap "" N to remove the trap for signal N
 
 GSED=`(which 'gsed*'; which 'sed*') | while read GSED; do "$GSED" -nu "{ p$NL q$NL}" </dev/null && echo $GSED && break; done`
 "$GSED" -nu "{ p$NL q$NL}" </dev/null || die "we need a sed that takes the '-nu' options, but $GSED doesn't"
@@ -109,6 +108,7 @@ fi
 
 
 if $GAWK -F "$FIELD_SEP" -f $TMPDIR/fullPROG "$@"; then : # do nothing, just exit
+    trap "/bin/rm -rf $TMPDIR; exit" 0 1 2 3 15
 else
     STATUS=$?
     # egrep-like regular expression of exit status/signal names to ignore
@@ -119,7 +119,8 @@ else
     else # kill -l has the format of space-separated "HUP INT QUIT", etc...
 	kill -l | newlines | grep -v IOT | nl   # but note IOT is a duplicate of TRAP--both are signal 6
     fi | head -20 | egrep -i "$IGNORE" | awk '128+$1=='"$STATUS{good=1}END{exit !good}" && exit 0
-    echo "$BASENAME: gawk failed with status $STATUS; program and data are in directory $TMPDIR" >&2
-    trap "" 0 1 2 3 15 # do not remove file
+    ( echo "$BASENAME: gawk failed with status $STATUS; program and data are in directory $TMPDIR; working directory was"
+	pwd; echo "filenames were"; for i in "$@"; do echo "$i"; done) >&2
+    #trap "" 0 1 2 3 15 # do not remove file
     exit $STATUS
 fi
