updating hawk and misc.awk from NetGO

diff --git a/bin/hawk b/bin/hawk
--- a/bin/hawk
+++ b/bin/hawk
@@ -27,7 +27,14 @@ shift
 
 echo "`cat "$DIR/misc.awk"`$PROG" > $TMP
 
-if gawk -F "$TAB_CHAR" -f "$TMP" "$@"; then : # do nothing, just exit
+AWK=`(which gawk4 || which gawk) 2>/dev/null | head -1 | sed 's/\*//g'`
+if [ -x "$AWK" ] && $AWK --version 2>/dev/null | fgrep 'GNU Awk 4.' >/dev/null; then
+    :
+else
+    AWK=awk
+fi
+
+if $AWK -F "$TAB_CHAR" -f "$TMP" "$@"; then : # do nothing, just exit
 else
     STATUS=$?
     [ $STATUS -le 3 ] && exit $STATUS
@@ -38,8 +45,8 @@ else
 	kill -l | tr "$TAB" "$NL"
     else # kill -l has the format of space-separated "HUP INT QUIT", etc...
 	kill -l | newlines | grep -v IOT | nl   # but note IOT is a duplicate of TRAP--both are signal 6
-    fi | head -20 | egrep -i "$IGNORE" | awk '128+$1=='"$STATUS{good=1}END{exit !good}" && exit 0
-    echo "gawk failed with status $STATUS program file is in file $TMP" >&2
+    fi | head -20 | egrep -i "$IGNORE" | $AWK '128+$1=='"$STATUS{good=1}END{exit !good}" && exit 0
+    echo "$AWK failed with status $STATUS program file is in file $TMP" >&2
     trap "" 0 1 2 3 15 # do not remove file
     exit $STATUS
 fi
